<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>XML Sitemap - Yakuza EV</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">
		body {
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			color: #333;
			max-width: 75rem;
			margin: 0 auto;
			padding: 2rem;
		}
		h1 {
			color: #000;
			font-size: 1.5rem;
			font-weight: 600;
		}
		p {
			color: #666;
			font-size: 0.875rem;
		}
		a {
			color: #05809e;
			text-decoration: none;
		}
		a:hover {
			text-decoration: underline;
		}
		table {
			width: 100%;
			border-collapse: collapse;
			margin-top: 1rem;
		}
		th {
			text-align: left;
			padding: 0.75rem;
			background: #f7f7f7;
			border-bottom: 1px solid #ddd;
			font-size: 0.875rem;
		}
		td {
			padding: 0.75rem;
			border-bottom: 1px solid #eee;
			font-size: 0.875rem;
		}
		tr:hover td {
			background: #fafafa;
		}
	</style>
</head>
<body>
	<h1>XML Sitemap</h1>
	<p>This is a XML Sitemap generated for search engines like Google, Bing, and Yahoo.</p>
	<p>Generated by Yakuza EV</p>
	<xsl:choose>
		<xsl:when test="sitemap:sitemapindex">
			<p>This sitemap index contains <xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/> sitemaps.</p>
			<table>
				<thead>
					<tr>
						<th>Sitemap</th>
						<th>Last Modified</th>
					</tr>
				</thead>
				<tbody>
					<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
						<tr>
							<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
							<td><xsl:value-of select="sitemap:lastmod"/></td>
						</tr>
					</xsl:for-each>
				</tbody>
			</table>
		</xsl:when>
		<xsl:otherwise>
			<p>This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.</p>
			<table>
				<thead>
					<tr>
						<th>URL</th>
						<th>Last Modified</th>
					</tr>
				</thead>
				<tbody>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td><a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a></td>
							<td><xsl:value-of select="sitemap:lastmod"/></td>
						</tr>
					</xsl:for-each>
				</tbody>
			</table>
		</xsl:otherwise>
	</xsl:choose>
</body>
</html>
</xsl:template>
</xsl:stylesheet>