<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0"
	xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
	xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
	xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
<xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
<xsl:template match="/">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>XML Sitemap - Yakuza EV</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
	<style type="text/css">
		body {
			font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
			color: #333;
			max-width: 75rem;
			margin: 0 auto;
			padding: 2rem;
			background: #f9f9f9;
		}
		.header {
			background: #a4286a;
			color: white;
			padding: 1.5rem 2rem;
			margin: -2rem -2rem 2rem -2rem;
		}
		.header h1 {
			color: white;
			font-size: 1.25rem;
			font-weight: 400;
			margin: 0;
		}
		.header p {
			color: rgba(255,255,255,0.8);
			font-size: 0.875rem;
			margin: 0.5rem 0 0 0;
		}
		.header a {
			color: white;
		}
		.content {
			background: white;
			padding: 1.5rem;
			border-radius: 4px;
			box-shadow: 0 1px 3px rgba(0,0,0,0.1);
		}
		.info {
			color: #666;
			font-size: 0.875rem;
			margin-bottom: 1rem;
		}
		table {
			width: 100%;
			border-collapse: collapse;
		}
		th {
			text-align: left;
			padding: 0.75rem 1rem;
			background: #f7f7f7;
			border-bottom: 1px solid #ddd;
			font-size: 0.8rem;
			font-weight: 600;
			text-transform: uppercase;
			color: #555;
		}
		td {
			padding: 0.75rem 1rem;
			border-bottom: 1px solid #eee;
			font-size: 0.875rem;
		}
		tr:hover td {
			background: #fafafa;
		}
		a {
			color: #a4286a;
			text-decoration: none;
		}
		a:hover {
			text-decoration: underline;
		}
		.icon {
			display: inline-block;
			width: 18px;
			height: 18px;
			margin-right: 8px;
			vertical-align: middle;
		}
		.icon-page {
			background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23a4286a'%3E%3Cpath d='M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8l-6-6zm4 18H6V4h7v5h5v11z'/%3E%3C/svg%3E") no-repeat center;
		}
		.icon-post {
			background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23a4286a'%3E%3Cpath d='M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-5 14H7v-2h7v2zm3-4H7v-2h10v2zm0-4H7V7h10v2z'/%3E%3C/svg%3E") no-repeat center;
		}
		.icon-product {
			background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23a4286a'%3E%3Cpath d='M18.36 9l.6 3H5.04l.6-3h12.72M20 4H4v2h16V4zm0 3H4l-1 5v2h1v6h10v-6h4v6h2v-6h1v-2l-1-5zM6 18v-4h6v4H6z'/%3E%3C/svg%3E") no-repeat center;
		}
		.icon-url {
			background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' fill='%23a4286a'%3E%3Cpath d='M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7c-2.76 0-5 2.24-5 5s2.24 5 5 5h4v-1.9H7c-1.71 0-3.1-1.39-3.1-3.1zM8 13h8v-2H8v2zm9-6h-4v1.9h4c1.71 0 3.1 1.39 3.1 3.1s-1.39 3.1-3.1 3.1h-4V17h4c2.76 0 5-2.24 5-5s-2.24-5-5-5z'/%3E%3C/svg%3E") no-repeat center;
		}
	</style>
</head>
<body>
	<div class="header">
		<h1>XML Sitemap</h1>
		<p>Generated by Yakuza EV - <a href="https://yakuzaev.vercel.app">https://yakuzaev.vercel.app</a></p>
	</div>
	<div class="content">
	<xsl:choose>
		<xsl:when test="sitemap:sitemapindex">
			<p class="info">This XML Sitemap Index file contains <strong><xsl:value-of select="count(sitemap:sitemapindex/sitemap:sitemap)"/></strong> sitemaps.</p>
			<table>
				<thead>
					<tr>
						<th>Sitemap</th>
						<th>Last Modified</th>
					</tr>
				</thead>
				<tbody>
					<xsl:for-each select="sitemap:sitemapindex/sitemap:sitemap">
						<tr>
							<td>
								<xsl:choose>
									<xsl:when test="contains(sitemap:loc, 'page-sitemap')">
										<span class="icon icon-page"></span>
									</xsl:when>
									<xsl:when test="contains(sitemap:loc, 'post-sitemap')">
										<span class="icon icon-post"></span>
									</xsl:when>
									<xsl:when test="contains(sitemap:loc, 'product-sitemap')">
										<span class="icon icon-product"></span>
									</xsl:when>
									<xsl:otherwise>
										<span class="icon icon-url"></span>
									</xsl:otherwise>
								</xsl:choose>
								<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
							</td>
							<td><xsl:value-of select="sitemap:lastmod"/></td>
						</tr>
					</xsl:for-each>
				</tbody>
			</table>
		</xsl:when>
		<xsl:otherwise>
			<p class="info">This XML Sitemap contains <strong><xsl:value-of select="count(sitemap:urlset/sitemap:url)"/></strong> URLs.</p>
			<table>
				<thead>
					<tr>
						<th>URL</th>
						<th>Last Modified</th>
					</tr>
				</thead>
				<tbody>
					<xsl:for-each select="sitemap:urlset/sitemap:url">
						<tr>
							<td>
								<span class="icon icon-url"></span>
								<a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
							</td>
							<td><xsl:value-of select="sitemap:lastmod"/></td>
						</tr>
					</xsl:for-each>
				</tbody>
			</table>
		</xsl:otherwise>
	</xsl:choose>
	</div>
</body>
</html>
</xsl:template>
</xsl:stylesheet>