import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";

interface SitemapEntry {
  loc: string;
  lastmod: string;
}

const SitemapXML = () => {
  const [sitemaps, setSitemaps] = useState<SitemapEntry[]>([]);
  const baseUrl = window.location.origin;

  useEffect(() => {
    const generateSitemaps = async () => {
      const today = new Date().toISOString().split('T')[0];
      const sitemapList: SitemapEntry[] = [];

      // Page sitemap
      sitemapList.push({
        loc: `${baseUrl}/page-sitemap.xml`,
        lastmod: today,
      });

      // Product sitemap
      const { data: products } = await supabase
        .from('products')
        .select('updated_at')
        .eq('is_active', true)
        .order('updated_at', { ascending: false })
        .limit(1);

      if (products && products.length > 0) {
        sitemapList.push({
          loc: `${baseUrl}/product-sitemap.xml`,
          lastmod: new Date(products[0].updated_at).toISOString().split('T')[0],
        });
      }

      // Blog sitemap
      const { data: blogs } = await supabase
        .from('blog_posts')
        .select('updated_at')
        .eq('status', 'published')
        .order('updated_at', { ascending: false })
        .limit(1);

      if (blogs && blogs.length > 0) {
        sitemapList.push({
          loc: `${baseUrl}/blog-sitemap.xml`,
          lastmod: new Date(blogs[0].updated_at).toISOString().split('T')[0],
        });
      }

      // Category sitemap
      const { data: categories } = await supabase
        .from('categories')
        .select('updated_at')
        .order('updated_at', { ascending: false })
        .limit(1);

      if (categories && categories.length > 0) {
        sitemapList.push({
          loc: `${baseUrl}/category-sitemap.xml`,
          lastmod: new Date(categories[0].updated_at).toISOString().split('T')[0],
        });
      }

      setSitemaps(sitemapList);
    };

    generateSitemaps();
  }, [baseUrl]);

  return (
    <div style={{ fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif', padding: '20px 40px', maxWidth: '1200px', margin: '0 auto' }}>
      <h1 style={{ fontSize: '48px', fontWeight: '300', marginBottom: '20px', color: '#333' }}>
        XML Sitemap
      </h1>
      
      <p style={{ fontSize: '16px', marginBottom: '10px', color: '#666' }}>
        Generated by <span style={{ color: '#a4286a', fontWeight: '600' }}>Yoast SEO</span>, this is an XML Sitemap, meant for consumption by search engines.
      </p>
      
      <p style={{ fontSize: '16px', marginBottom: '30px', color: '#666' }}>
        You can find more information about XML sitemaps on{' '}
        <a href="https://www.sitemaps.org" style={{ color: '#a4286a', textDecoration: 'none' }}>
          sitemaps.org
        </a>.
      </p>
      
      <p style={{ fontSize: '16px', marginBottom: '30px', color: '#333', fontWeight: '500' }}>
        This XML Sitemap Index file contains {sitemaps.length} sitemaps.
      </p>

      <table style={{ width: '100%', borderCollapse: 'collapse', backgroundColor: '#fff', border: '1px solid #ddd' }}>
        <thead>
          <tr style={{ backgroundColor: '#f7f7f7', borderBottom: '2px solid #ddd' }}>
            <th style={{ padding: '15px', textAlign: 'left', fontWeight: '600', fontSize: '14px', color: '#333' }}>
              Sitemap
            </th>
            <th style={{ padding: '15px', textAlign: 'left', fontWeight: '600', fontSize: '14px', color: '#333' }}>
              Last Modified
            </th>
          </tr>
        </thead>
        <tbody>
          {sitemaps.map((sitemap, index) => (
            <tr key={index} style={{ borderBottom: '1px solid #eee' }}>
              <td style={{ padding: '15px', fontSize: '14px', color: '#666' }}>
                <a href={sitemap.loc} style={{ color: '#a4286a', textDecoration: 'none' }}>
                  {sitemap.loc}
                </a>
              </td>
              <td style={{ padding: '15px', fontSize: '14px', color: '#666' }}>
                {sitemap.lastmod} {new Date(sitemap.lastmod + 'T00:00:00').toLocaleTimeString('en-US', { hour12: false })} +00:00
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default SitemapXML;
