// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqhwoizjlvjdiuemirsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxaHdvaXpqbHZqZGl1ZW1pcnN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjM0NzgsImV4cCI6MjA3MjM5OTQ3OH0.9Bl5oXzeYvdWGRkUV-aFNQVYbNoSVvSX-ONIMa7wN-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});